const $=id=>document.getElementById(id);
const state={conversation:null,scene:'battle_review',providers:[],pending:[],assets:[],messages:[],events:[],ws:null,busy:false,progress:[],session:null,config:null};
const SCENE_NAME={battle_review:'战斗录像复盘',balance:'数值平衡诊断',regression:'版本回归验证',npc:'角色与 NPC 分析',content_compare:'多素材对比'};
const ICON={image:'▧',video:'▶',audio:'♫',text:'⌘',file:'＋',replay:'↻'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function apiUrl(path){return path}
async function api(path,opt={}){const r=await fetch(apiUrl(path),{credentials:'same-origin',headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})},...opt});if(!r.ok){let t=await r.text();let msg=t;try{msg=JSON.parse(t).detail||t}catch{}const err=new Error(msg||`${r.status}`);err.status=r.status;if(r.status===401&&state.config?.auth_required)showAuthModal();throw err}return r.json()}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}

function applySession(session){state.session=session;const workspace=session?.workspace;$('workspaceName').textContent=workspace?.name||'本地演示空间';const email=session?.user?.email||'demo@local';$('userAvatar').textContent=(email.split('@')[0].slice(0,1)||'游').toUpperCase();$('userAvatar').title=`${email} · ${session?.user?.role||'member'}`}
function showAuthModal(){if($('authModal'))$('authModal').hidden=false}
function hideAuthModal(){if($('authModal'))$('authModal').hidden=true}
function switchAuthTab(name){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===name));$('loginForm').hidden=name!=='login';$('registerForm').hidden=name!=='register'}
async function ensureSession(){state.config=await api('/api/config');try{const session=await api('/api/auth/me');applySession(session);hideAuthModal();return true}catch(err){if(err.status===401&&state.config.auth_required){showAuthModal();return false}throw err}}
async function loadServiceHealth(){try{const h=await api('/api/health');const el=$('serviceStatus');el.querySelector('span').textContent=`服务正常 · ${h.storage}/${h.queue}`;el.classList.remove('bad')}catch{const el=$('serviceStatus');el.querySelector('span').textContent='服务异常';el.classList.add('bad')}}
async function bootWorkspace(){await Promise.all([loadProviders(),loadConversations(),loadServiceHealth()]);const rows=await api('/api/conversations');const requested=new URLSearchParams(location.search).get('conversation');if(requested){try{await openConversation(requested);return}catch{toast('任务链接已失效，已打开最近任务')}}if(rows.length)await openConversation(rows[0].id);else await newConversation('battle_review')}
function bindAuth(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>switchAuthTab(b.dataset.authTab));$('loginForm').onsubmit=async e=>{e.preventDefault();try{const session=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});applySession(session);hideAuthModal();toast('登录成功');await bootWorkspace()}catch(err){toast(err.message)}};$('registerForm').onsubmit=async e=>{e.preventDefault();try{const session=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('registerName').value.trim(),workspace_name:$('registerWorkspace').value.trim(),email:$('registerEmail').value.trim(),password:$('registerPassword').value})});applySession(session);hideAuthModal();toast('Workspace 已创建');await bootWorkspace()}catch(err){toast(err.message)}};$('userAvatar').onclick=async()=>{if(!state.config?.auth_required)return toast(state.session?.workspace?.name||'本地演示空间');try{await api('/api/auth/logout',{method:'POST',body:JSON.stringify({})});state.session=null;state.conversation=null;state.ws?.close();showAuthModal();toast('已退出登录')}catch(err){toast(err.message)}}}

function fmtSize(n){if(n<1024)return `${n}B`;if(n<1024*1024)return `${(n/1024).toFixed(1)}KB`;return `${(n/1024/1024).toFixed(1)}MB`}
function fmtTime(ts){const d=new Date(ts*1000);return d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}
function kindOf(a){return a?.meta?.kind||(/image/.test(a?.mime)?'image':/video/.test(a?.mime)?'video':/audio/.test(a?.mime)?'audio':'file')}
function md(text){let s=esc(text||'');s=s.replace(/^###\s+(.+)$/gm,'<h3>$1</h3>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');const lines=s.split('\n'),out=[];let inList=false;for(const line of lines){const m=line.match(/^\s*(\d+)\.\s+(.+)$/);if(m){if(!inList){out.push('<ol>');inList=true}out.push(`<li>${m[2]}</li>`)}else{if(inList){out.push('</ol>');inList=false}if(line.trim())out.push(`<p>${line}</p>`)}}if(inList)out.push('</ol>'); return out.join('')}
function setScene(scene){state.scene=scene;document.querySelectorAll('.scene-item').forEach(x=>x.classList.toggle('active',x.dataset.scene===scene));$('conversationTitle').textContent=SCENE_NAME[scene]||'分析任务';$('conversationMeta').textContent='把素材放进来，直接问';}
async function loadProviders(){state.providers=await api('/api/providers');const sel=$('providerSelect');sel.innerHTML=state.providers.map(p=>`<option value="${esc(p.key)}" ${p.key!=='auto'&&p.key!=='demo'&&!p.configured?'disabled':''}>${esc(p.name)}${p.key!=='auto'&&p.key!=='demo'&&!p.configured?' · 未配置':''}</option>`).join('');renderProviderModal()}
function renderProviderModal(){$('providerGrid').innerHTML=state.providers.filter(p=>!['auto'].includes(p.key)).map(p=>`<div class="provider-card"><div class="provider-logo">${esc((p.name||'?').slice(0,2))}</div><div><b>${esc(p.name)} <small>${esc(p.vendor)}</small></b><p>${esc(p.note||'')}</p><small>${p.multimodal?'支持图像/多模态':'文本推理'}${p.supports_video?' · 视频':''}${p.supports_audio?' · 音频':''}${p.model?' · '+esc(p.model):''}</small></div><span class="provider-status ${p.configured?'ok':''}">${p.configured?'可用':'未配置'}</span></div>`).join('')}
async function loadConversations(){const rows=await api('/api/conversations');$('conversationList').innerHTML=rows.map(c=>`<div class="conv-item ${state.conversation?.id===c.id?'active':''}" data-id="${c.id}"><span></span><div><b>${esc(c.title)}</b><small>${esc(SCENE_NAME[c.scene]||c.scene)}</small></div></div>`).join('')||'<div class="empty-side">还没有历史任务。</div>';document.querySelectorAll('.conv-item').forEach(x=>x.onclick=()=>openConversation(x.dataset.id))}
function syncConversationUrl(id){if(!id)return;const u=new URL(location.href);u.searchParams.set('conversation',id);history.replaceState(null,'',u)}
async function newConversation(scene=state.scene){const c=await api('/api/conversations',{method:'POST',body:JSON.stringify({title:SCENE_NAME[scene]||'新的分析任务',scene})});state.conversation=c;state.messages=[];state.assets=[];state.events=[];state.progress=[];if(state.ws)state.ws.close();syncConversationUrl(c.id);renderConversation();connectConversation();loadConversations();return c}
async function openConversation(id){const c=await api(`/api/conversations/${id}`);state.conversation=c;state.messages=c.messages||[];state.assets=c.assets||[];state.events=c.events||[];state.progress=[];setScene(c.scene||'battle_review');if(state.ws)state.ws.close();syncConversationUrl(c.id);renderConversation();connectConversation();loadConversations()}
function renderConversation(){$('welcomePanel').hidden=state.messages.length>0;$('conversationTitle').textContent=state.conversation?.title||SCENE_NAME[state.scene];$('conversationMeta').textContent=state.messages.length?`${state.messages.length} 条消息 · ${state.assets.length} 份素材`:'把素材放进来，直接问';$('messageList').innerHTML=state.messages.map(renderMessage).join('');renderAssets();renderEventHistory();const lastAnswer=[...state.messages].reverse().find(m=>m.role==='assistant');if(lastAnswer?.payload){renderEvidence(lastAnswer.payload.evidence||[]);renderSuggestions(lastAnswer.payload.suggestions||[]);}scrollBottom(false)}
function renderMessage(m){const payload=m.payload||{};const assetIds=payload.asset_ids||[];const msgAssets=assetIds.map(id=>state.assets.find(a=>a.id===id)).filter(Boolean);if(m.role==='user')return `<div class="msg user"><div class="msg-body"><div class="msg-content">${esc(m.content)}</div>${renderMsgAssets(msgAssets)}</div></div>`;return `<div class="msg assistant"><div class="msg-body"><div class="msg-label"><span class="assistant-logo">灵</span><b>灵境</b><span>${m.created_at?fmtTime(m.created_at):''}</span></div><div class="msg-content">${md(m.content)}</div><div class="answer-foot"><span class="answer-provider">由 ${esc(payload.provider||'工作台')} 完成</span><button class="answer-action" onclick="navigator.clipboard?.writeText(${JSON.stringify(m.content)})">复制</button></div></div></div>`}
function renderMsgAssets(rows){if(!rows.length)return'';return `<div class="msg-assets">${rows.map(a=>{const k=kindOf(a);const visual=k==='image'?`<img class="msg-asset-thumb" src="/api/assets/${a.id}/file"/>`:k==='video'?`<div class="msg-asset-video"><img src="/api/assets/${a.id}/preview/0"/><span>▶</span></div>`:`<i>${ICON[k]||'＋'}</i>`;return `<div class="msg-asset ${k}">${visual}<div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}</small></div></div>`}).join('')}</div>`}
function kindLabel(a){const k=kindOf(a),m=a.meta||{};if(k==='video')return `视频${m.duration?' · '+m.duration+'s':''}`;if(k==='image')return `图片${m.width?' · '+m.width+'×'+m.height:''}`;if(k==='audio')return `音频${m.duration?' · '+m.duration+'s':''}`;if(k==='text')return `文本 · ${m.lines||0} 行`;return fmtSize(a.size||0)}
function renderPending(){const box=$('pendingAssets');box.hidden=!state.pending.length;box.innerHTML=state.pending.map((a,i)=>`<div class="pending-asset">${kindOf(a)==='image'?`<img class="thumb" src="/api/assets/${a.id}/file"/>`:`<span class="thumb">${ICON[kindOf(a)]||'＋'}</span>`}<div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}</small></div><button data-rm="${i}">×</button></div>`).join('');box.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.pending.splice(Number(b.dataset.rm),1);renderPending()})}
function renderAssets(){const rows=state.assets;$('assetList').innerHTML=rows.length?rows.map(a=>`<div class="asset-card"><div class="asset-icon">${ICON[kindOf(a)]||'＋'}</div><div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}<br>${fmtSize(a.size||0)}</small></div></div>`).join(''):'<div class="empty-side">还没有上传素材。</div>'}
function renderEvidence(rows=[]){$('evidenceList').innerHTML=rows.length?rows.map(e=>{const a=e.asset_id?state.assets.find(x=>x.id===e.asset_id):null;const k=e.type||kindOf(a);let media='';if(a&&k==='image')media=`<div class="evidence-media"><img src="/api/assets/${a.id}/file"/></div>`;else if(a&&k==='video')media=`<div class="evidence-media video"><img src="/api/assets/${a.id}/preview/0"/><span>▶ 关键帧</span></div>`;else if(a&&k==='audio')media=`<div class="evidence-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><span>${a.meta?.duration||0}s</span></div>`;else if(a&&k==='text'&&a.meta?.preview)media=`<pre class="evidence-log">${esc(a.meta.preview.split('\n').slice(0,3).join('\n'))}</pre>`;return `<div class="evidence-card rich">${media}<div class="evidence-info"><div class="evidence-icon">${ICON[k]||'◇'}</div><div><em>${esc(e.label||'证据')}</em><b>${esc(e.title||'')}</b><small>${k==='replay'?'已完成同条件复核':'已关联到当前结论'}</small></div></div></div>`}).join(''):'<div class="empty-side">完成一次分析后显示。</div>'}
function renderSuggestions(rows=[]){$('suggestionList').innerHTML=(rows.length?rows:['继续追问','补充素材','整理成结论摘要']).map(x=>`<button>${esc(x)}</button>`).join('');$('suggestionList').querySelectorAll('button').forEach(b=>b.onclick=()=>{ $('messageInput').value=b.textContent; autoSize(); $('messageInput').focus() })}
function renderEventHistory(){const progress=state.events.filter(e=>e.type==='progress');if(progress.length){state.progress=progress.map(e=>e.payload);renderProgress()}}
function renderProgress(){const rows=state.progress;const last=rows.at(-1);if(last){$('taskState').textContent=last.step;$('taskPercent').textContent=`${last.percent||0}%`;$('taskProgress').style.width=`${last.percent||0}%`;document.querySelector('.task-state-card').className='task-state-card '+((last.percent||0)>=100?'done':'running')}$('progressList').innerHTML=rows.length?rows.map((p,i)=>`<div class="progress-row ${i<rows.length-1||(p.percent||0)>=100?'done':''}"><span>${i<rows.length-1||(p.percent||0)>=100?'✓':i+1}</span><div><b>${esc(p.step)}</b><small>${esc(p.detail||'')}</small></div></div>`).join(''):'<div class="progress-empty"><span>✓</span><b>准备好了</b><p>发一句问题，或者先上传素材。</p></div>'}
function connectConversation(){if(!state.conversation)return;const proto=location.protocol==='https:'?'wss':'ws';state.ws=new WebSocket(`${proto}://${location.host}/ws/conversations/${state.conversation.id}`);state.ws.onmessage=e=>{const ev=JSON.parse(e.data);handleEvent(ev)};state.ws.onerror=()=>{} }
function handleEvent(ev){if(ev.type==='heartbeat')return;if(ev.id && state.events.some(x=>x.id===ev.id))return;state.events.push(ev);if(ev.type==='progress'){state.progress.push(ev.payload);renderProgress();$('thinkingCard').hidden=false;$('thinkingStep').textContent=ev.payload.step;$('thinkingDetail').textContent=ev.payload.detail;$('thinkingPercent').textContent=`${ev.payload.percent||0}%`;$('thinkingBar').style.width=`${ev.payload.percent||0}%`;scrollBottom()}if(ev.type==='answer.ready'){state.busy=false;$('sendBtn').disabled=false;$('thinkingCard').hidden=true;const m=ev.payload.message;state.messages.push(m);const result=ev.payload.result||{};renderConversation();renderEvidence(result.evidence||[]);renderSuggestions(result.suggestions||[]);$('taskState').textContent='分析完成';$('taskPercent').textContent='100%';$('taskProgress').style.width='100%';document.querySelector('.task-state-card').className='task-state-card done';loadConversations()}if(ev.type==='answer.error'){state.busy=false;$('sendBtn').disabled=false;$('thinkingCard').hidden=true;toast(ev.payload.message||'处理失败')} }
async function uploadFiles(files){if(!files?.length)return;if(!state.conversation)await newConversation(state.scene);for(const file of files){const fd=new FormData();fd.append('file',file);fd.append('conversation_id',state.conversation.id);toast(`正在添加 ${file.name}`);try{const a=await api('/api/assets',{method:'POST',body:fd});state.pending.push(a);if(!state.assets.some(x=>x.id===a.id))state.assets.push(a);renderPending();renderAssets()}catch(err){toast(`上传失败：${err.message}`)}}}
async function sendMessage(){const input=$('messageInput');const text=input.value.trim();if(!text||state.busy)return;if(!state.conversation)await newConversation(state.scene);state.busy=true;$('sendBtn').disabled=true;const assetIds=state.pending.map(a=>a.id);const user={id:'local-'+Date.now(),role:'user',content:text,payload:{asset_ids:assetIds},created_at:Date.now()/1000};state.messages.push(user);input.value='';autoSize();state.pending=[];renderPending();$('welcomePanel').hidden=true;renderConversation();$('thinkingCard').hidden=false;$('thinkingStep').textContent='接收任务';$('thinkingDetail').textContent='正在整理问题和素材';$('thinkingPercent').textContent='5%';$('thinkingBar').style.width='5%';state.progress=[];renderProgress();scrollBottom();try{await api(`/api/conversations/${state.conversation.id}/messages`,{method:'POST',body:JSON.stringify({content:text,asset_ids:assetIds,provider:$('providerSelect').value})})}catch(err){state.busy=false;$('sendBtn').disabled=false;$('thinkingCard').hidden=true;toast(err.message)}}
function scrollBottom(smooth=true){requestAnimationFrame(()=>$('chatScroll').scrollTo({top:$('chatScroll').scrollHeight,behavior:smooth?'smooth':'auto'}))}
function autoSize(){const t=$('messageInput');t.style.height='auto';t.style.height=Math.min(130,t.scrollHeight)+'px'}
function setRightPanel(name){document.querySelectorAll('.right-tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.right-panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`))}
function bind(){bindAuth();document.querySelectorAll('.scene-item').forEach(x=>x.onclick=()=>{setScene(x.dataset.scene);newConversation(x.dataset.scene)});document.querySelectorAll('.quick-card').forEach(x=>x.onclick=()=>{$('messageInput').value=x.dataset.prompt;autoSize();$('messageInput').focus()});document.querySelectorAll('.right-tab').forEach(x=>x.onclick=()=>setRightPanel(x.dataset.panel));$('newTaskBtn').onclick=()=>newConversation(state.scene);$('refreshConvBtn').onclick=loadConversations;$('sendBtn').onclick=sendMessage;$('messageInput').oninput=autoSize;$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};document.querySelectorAll('.attach-btn').forEach(b=>b.onclick=()=>{$('fileInput').accept=b.dataset.accept;$('fileInput').click()});$('fileInput').onchange=e=>{uploadFiles([...e.target.files]);e.target.value=''};let drag=0;window.addEventListener('dragenter',e=>{e.preventDefault();drag++;$('dropMask').hidden=false});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',e=>{e.preventDefault();drag--;if(drag<=0){drag=0;$('dropMask').hidden=true}});window.addEventListener('drop',e=>{e.preventDefault();drag=0;$('dropMask').hidden=true;uploadFiles([...e.dataTransfer.files])});$('providerBtn').onclick=()=>$('providerModal').hidden=false;$('settingsBtn').onclick=()=>$('providerModal').hidden=false;$('providerModal').onclick=e=>{if(e.target===$('providerModal')||e.target.closest('.modal-close'))$('providerModal').hidden=true};$('assetLibraryBtn').onclick=()=>setRightPanel('assets');$('shareBtn').onclick=async()=>{if(!state.conversation)return toast('请先创建任务');syncConversationUrl(state.conversation.id);try{await navigator.clipboard.writeText(location.href);toast('已复制当前任务链接')}catch{toast('当前浏览器不允许自动复制，请复制地址栏链接')}};$('moreBtn').onclick=()=>toast('导出报告与归档功能尚未开放');}
async function boot(){bind();setScene('battle_review');try{const ready=await ensureSession();if(ready)await bootWorkspace()}catch(err){console.error(err);toast('服务连接失败，请检查后端')}}
boot();
