from abc import ABC,abstractmethod
class GameEnvironment(ABC):
 @abstractmethod
 def reset(self,scenario,seed):...
 @abstractmethod
 def legal_actions(self,state):...
 @abstractmethod
 def step(self,action):...
 @abstractmethod
 def snapshot(self):...
 @abstractmethod
 def restore(self,snapshot):...
 @abstractmethod
 def clone(self,seed_offset=0):...
