import fs from 'node:fs';

const backend = process.env.WORLDFORGE_URL || 'http://127.0.0.1:8765';
const frontend = process.env.WORLDFORGE_FRONTEND || backend;
const wsBase = backend.replace(/^http/, 'ws');
const report = { started_at: new Date().toISOString(), checks: {}, events: {}, backend, frontend };
function assert(cond, msg){ if(!cond) throw new Error(msg); }
async function json(path, opts={}){const r=await fetch(backend+path,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts});assert(r.ok, `${path} -> ${r.status}`); return r.json();}
const html=await (await fetch(frontend+'/')).text();
const js=await (await fetch(frontend+'/app.js').catch(()=>fetch(frontend+'/assets/app.js'))).text();
assert(html.includes('WorldForge'),'frontend brand missing');assert(html.includes('游戏自主智能体验证与演进平台'),'Chinese product shell missing');assert(js.includes('API_BASE'),'separate frontend/backend routing missing');assert(js.includes('openSocket'),'frontend websocket client missing');report.checks.frontend_server=true;
const health=await json('/api/health');const model=await json('/api/model');const scenarios=await json('/api/scenarios');const runtime=await json('/api/runtime');assert(health.status==='ok','health failed');assert(health.external_model_api===false,'external model API must be disabled');assert(model.ownership==='项目自研' && model.external_api===false,'own-model contract broken');assert(scenarios.length>=4,'scenario inventory incomplete');assert(runtime.plugins.some(p=>p.name==='counterfactual-brancher'),'counterfactual plugin missing');assert(runtime.plugins.some(p=>p.name==='recursive-scheduler'),'recursive scheduler missing');assert(runtime.plugins.some(p=>p.name==='action-sandbox'),'action sandbox missing');report.checks.backend_contract=true;
const run=await json('/api/runs',{method:'POST',body:JSON.stringify({scenario_id:'loot_exploit', seed:17, max_steps:18, branch_width:4,rollout_horizon:3, rollouts_per_branch:3, enable_counterfactual:true,enable_recursive_agents:true, enable_evolution:true})});report.session_id=run.session_id;assert(run.model==='WorldForge-M1','runtime did not use WorldForge-M1');
const events=[];await new Promise((resolve,reject)=>{const ws=new WebSocket(`${wsBase}/ws/runs/${run.session_id}`);const timer=setTimeout(()=>{ws.close();reject(new Error('websocket run timeout'));},45000);ws.onmessage=(m)=>{const e=JSON.parse(m.data);if(e.event_type==='heartbeat') return;events.push(e);if(e.event_type==='run.completed'){clearTimeout(timer); ws.close(); resolve();}};ws.onerror=()=>{clearTimeout(timer);reject(new Error('websocket error'));};});
const types=events.reduce((a,e)=>(a[e.event_type]=(a[e.event_type]||0)+1,a),{});for(const t of ['model.policy','decision.committed','counterfactual.evaluated','subagent.tree','sandbox.checked','action.executed','run.completed']){assert(types[t]>0,`missing streamed event: ${t}`);}assert(types['qa.finding']>0,'adversarial QA probe did not produce a finding');report.events=types;report.checks.websocket_interaction=true;
const verify=await json(`/api/runs/${run.session_id}/verify`);const decision=await json(`/api/runs/${run.session_id}/decision-space`);const runReport=await json(`/api/runs/${run.session_id}/report`);assert(verify.hash_chain_valid===true,'event hash chain invalid');assert(decision.world && decision.model && decision.branches && decision.decision,'decision-space incomplete');assert(runReport.metrics.hash_chain_valid===true,'report hash chain invalid');assert(runReport.metrics.finding_count>0,'report lost QA finding');report.checks.hash_chain=true;report.checks.decision_space=true;report.run_report=runReport.metrics;
const selfplay=await json('/api/selfplay/loot_exploit?seeds=3');assert(selfplay.population?.length===4,'self-play population incomplete');report.selfplay={hardest_profile:selfplay.hardest_profile,priority:selfplay.priority};report.checks.selfplay=true;
const bench=await json('/api/benchmarks',{method:'POST',body:JSON.stringify({seeds:4})});assert(bench.rows?.length===4,'benchmark rows missing');const wf=bench.rows.find(x=>x.harness==='WorldForge Harness');const verifier=bench.rows.find(x=>x.harness==='M1 + Verifier');assert(wf && verifier && wf.success_rate>=verifier.success_rate,'full harness should not regress verifier baseline in smoke benchmark');report.benchmark=bench.rows;report.checks.benchmark=true;
report.finished_at=new Date().toISOString();fs.mkdirSync('outputs',{recursive:true});fs.writeFileSync('outputs/e2e_report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
